version: '3.4'

services:

  backend:
    container_name: back_container
    build: 
      backend/   
    command:
      npm run start    
    depends_on:
      - mysql_db
    environment:
      MYSQL_HOST: "mysql_db"
      JWT_SECRET_TOKEN: ${JWT_SECRET_TOKEN:-your_secret_token_here}
      CORS_ORIGIN_REGEX: http([s])?://localhost:3002
    ports:
      - 3001:3001

  frontend:
    container_name: front_container
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    environment:
      SERVER_ORIGIN: http://localhost:3001
    ports:
      - 3002:3002
    restart: on-failure
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tradeoffer_db
    ports:
      - "3307:3307"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mysql_db
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 30000:8080
    depends_on:
      - mysql_db
    